// Minimal example: load wasm-bindgen output generated by wasm-pack
// Assumes wasm-pack output is at editor/src/wasm/pkg/harmony_wasm.js

export async function initWasm(): Promise<any> {
  // dynamic import lets Vite include the JS glue and fetch the .wasm
  const pkg = await import('./wasm/pkg/harmony_wasm.js');
  // wasm-bindgen JS exports default init function in many cases
  if (typeof pkg.default === 'function') {
    await pkg.default();
  }
  return pkg;
}

// Usage example:
// (async () => {
//   const wasm = await initWasm();
//   console.log('wasm add', wasm.add(2,3));
// })();
