export const LAND_TERRAIN_SURFACE_RENDER_ORDER = 16
export const WATER_TERRAIN_SURFACE_RENDER_ORDER = 24

export const LANDFORM_SURFACE_WORLD_OFFSET = 0.008
export const LANDFORM_SURFACE_POLYGON_OFFSET_FACTOR = -2
export const LANDFORM_SURFACE_POLYGON_OFFSET_UNITS = -2

export const WATER_SURFACE_POLYGON_OFFSET_FACTOR = -4
export const WATER_SURFACE_POLYGON_OFFSET_UNITS = -4
export const WATER_SURFACE_WORLD_OFFSET = 0.012
