import {
  clampParticleSystemComponentProps,
  cloneParticleSystemComponentProps,
  DEFAULT_PARTICLE_BUDGET,
  DEFAULT_PARTICLE_EXPOSED_PARAMS,
  type ParticleSystemComponentProps,
} from './particleSchema'

export type ParticlePresetDefinition = {
  id: string
  label: string
  description: string
  props: ParticleSystemComponentProps
}

const PRESETS: ParticlePresetDefinition[] = [
  {
    id: 'groundAuraLite',
    label: 'Ground Aura Lite',
    description: 'Low-cost ring aura for ground highlights.',
    props: clampParticleSystemComponentProps({
      presetId: 'groundAuraLite',
      budget: { ...DEFAULT_PARTICLE_BUDGET, maxParticles: 72, cullDistance: 20, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#46d9ff', emissionRate: 12, burstCount: 16, radius: 0.9, speed: 1.2, lifetime: 1.4 },
      emitters: [
        {
          id: 'ground_ring',
          shape: 'sphere',
          radius: 0.85,
          emissionRate: 12,
          emissionBursts: 16,
          maxParticles: 72,
          particleSize: 0.16,
          lifetime: 1.4,
          speed: 1.2,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 0.5,
          color: '#46d9ff',
          color2: '#a8f6ff',
          alphaStart: 0.8,
          alphaEnd: 0,
          scaleStart: 0.65,
          scaleEnd: 0.15,
          position: { x: 0, y: 0.05, z: 0 },
          size: { x: 0.1, y: 0.1, z: 0.1 },
        },
      ],
    }),
  },
  {
    id: 'warpColumnLite',
    label: 'Warp Column Lite',
    description: 'Vertical portal-style particle column with safe mobile limits.',
    props: clampParticleSystemComponentProps({
      presetId: 'warpColumnLite',
      budget: { qualityTier: 'balanced', maxParticles: 96, spawnRateScale: 1, cullDistance: 28, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#74f5ff', emissionRate: 20, burstCount: 24, radius: 0.5, speed: 2.4, lifetime: 1.8, particleSize: 0.14 },
      emitters: [
        {
          id: 'column_core',
          shape: 'box',
          position: { x: 0, y: 0.8, z: 0 },
          size: { x: 0.32, y: 1.6, z: 0.32 },
          radius: 0.5,
          emissionRate: 20,
          emissionBursts: 24,
          maxParticles: 96,
          particleSize: 0.14,
          lifetime: 1.8,
          speed: 2.4,
          velocityMode: 'vector',
          direction: { x: 0, y: 1, z: 0 },
          spread: 0.35,
          color: '#74f5ff',
          color2: '#bafcff',
          alphaStart: 0.72,
          alphaEnd: 0,
          scaleStart: 0.85,
          scaleEnd: 0.3,
        },
      ],
    }),
  },
  {
    id: 'sparkBurstLite',
    label: 'Spark Burst Lite',
    description: 'One-shot spark burst with capped mobile burst counts.',
    props: clampParticleSystemComponentProps({
      presetId: 'sparkBurstLite',
      playback: { autoPlay: false, loop: false, startActive: false, prewarmSeconds: 0, softStopSeconds: 0.15 },
      budget: { qualityTier: 'mini-safe', maxParticles: 48, spawnRateScale: 1, cullDistance: 18, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#ffd16a', emissionRate: 0, burstCount: 28, radius: 0.15, speed: 4.5, lifetime: 0.7, particleSize: 0.09 },
      emitters: [
        {
          id: 'spark_burst',
          shape: 'point',
          position: { x: 0, y: 0.2, z: 0 },
          size: { x: 0, y: 0, z: 0 },
          radius: 0.15,
          emissionRate: 0,
          emissionBursts: 28,
          maxParticles: 48,
          particleSize: 0.09,
          lifetime: 0.7,
          speed: 4.5,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 2.4,
          color: '#ffd16a',
          color2: '#ff8f4f',
          alphaStart: 0.95,
          alphaEnd: 0,
          scaleStart: 1,
          scaleEnd: 0.2,
        },
      ],
    }),
  },
  {
    id: 'smokeLoopLite',
    label: 'Smoke Loop Lite',
    description: 'Slow drifting smoke tuned for low-frequency updates.',
    props: clampParticleSystemComponentProps({
      presetId: 'smokeLoopLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 64, spawnRateScale: 1, cullDistance: 22, updateHz: 24 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#c7d0d8', emissionRate: 8, burstCount: 10, radius: 0.45, speed: 0.8, lifetime: 2.2, particleSize: 0.26, opacity: 0.45 },
      render: { textureAssetId: null, blendMode: 'alpha', depthWrite: false, sortOffset: 0, renderMode: 'sprite' },
      emitters: [
        {
          id: 'smoke_loop',
          shape: 'box',
          position: { x: 0, y: 0.2, z: 0 },
          size: { x: 0.35, y: 0.2, z: 0.35 },
          radius: 0.45,
          emissionRate: 8,
          emissionBursts: 10,
          maxParticles: 64,
          particleSize: 0.26,
          lifetime: 2.2,
          speed: 0.8,
          velocityMode: 'vector',
          direction: { x: 0.1, y: 1, z: 0.1 },
          spread: 0.45,
          color: '#c7d0d8',
          color2: '#eef2f5',
          alphaStart: 0.45,
          alphaEnd: 0,
          scaleStart: 0.8,
          scaleEnd: 1.45,
        },
      ],
    }),
  },
  {
    id: 'rainCurtainLite',
    label: 'Rain Curtain Lite',
    description: 'Soft falling rain streaks for weather ambience.',
    props: clampParticleSystemComponentProps({
      presetId: 'rainCurtainLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 96, spawnRateScale: 0.8, cullDistance: 40, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#8fd7ff', emissionRate: 38, burstCount: 36, radius: 1.1, speed: 8.8, lifetime: 1.1, particleSize: 0.05, opacity: 0.48 },
      render: { textureAssetId: null, blendMode: 'alpha', depthWrite: false, sortOffset: 0, renderMode: 'sprite' },
      emitters: [
        {
          id: 'rain_field',
          shape: 'box',
          position: { x: 0, y: 3.2, z: 0 },
          size: { x: 4.5, y: 0.2, z: 4.5 },
          radius: 1.1,
          emissionRate: 38,
          emissionBursts: 36,
          maxParticles: 96,
          particleSize: 0.05,
          lifetime: 1.1,
          speed: 8.8,
          velocityMode: 'vector',
          direction: { x: 0, y: -1, z: 0 },
          spread: 0.18,
          color: '#8fd7ff',
          color2: '#d8f4ff',
          alphaStart: 0.5,
          alphaEnd: 0,
          scaleStart: 1,
          scaleEnd: 0.8,
        },
      ],
    }),
  },
  {
    id: 'snowDriftLite',
    label: 'Snow Drift Lite',
    description: 'Gentle snow flakes drifting downward with soft visibility.',
    props: clampParticleSystemComponentProps({
      presetId: 'snowDriftLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 72, spawnRateScale: 0.7, cullDistance: 42, updateHz: 24 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#ffffff', emissionRate: 14, burstCount: 12, radius: 1.25, speed: 0.9, lifetime: 4.2, particleSize: 0.14, opacity: 0.72 },
      render: { textureAssetId: null, blendMode: 'alpha', depthWrite: false, sortOffset: 0, renderMode: 'sprite' },
      emitters: [
        {
          id: 'snow_field',
          shape: 'box',
          position: { x: 0, y: 4, z: 0 },
          size: { x: 5.5, y: 0.25, z: 5.5 },
          radius: 1.25,
          emissionRate: 14,
          emissionBursts: 12,
          maxParticles: 72,
          particleSize: 0.14,
          lifetime: 4.2,
          speed: 0.9,
          velocityMode: 'vector',
          direction: { x: 0.05, y: -1, z: 0.04 },
          spread: 0.8,
          color: '#ffffff',
          color2: '#dce8f2',
          alphaStart: 0.72,
          alphaEnd: 0,
          scaleStart: 0.9,
          scaleEnd: 0.55,
        },
      ],
    }),
  },
  {
    id: 'leafFallLite',
    label: 'Leaf Fall Lite',
    description: 'Autumn leaves gently falling through the air.',
    props: clampParticleSystemComponentProps({
      presetId: 'leafFallLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 64, spawnRateScale: 0.6, cullDistance: 36, updateHz: 24 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#d89a43', emissionRate: 10, burstCount: 12, radius: 1.1, speed: 1.1, lifetime: 5.5, particleSize: 0.22, opacity: 0.9 },
      render: { textureAssetId: null, blendMode: 'alpha', depthWrite: false, sortOffset: 0, renderMode: 'sprite' },
      emitters: [
        {
          id: 'leaf_canopy',
          shape: 'box',
          position: { x: 0, y: 4.2, z: 0 },
          size: { x: 4.8, y: 0.3, z: 4.8 },
          radius: 1.1,
          emissionRate: 10,
          emissionBursts: 12,
          maxParticles: 64,
          particleSize: 0.22,
          lifetime: 5.5,
          speed: 1.1,
          velocityMode: 'vector',
          direction: { x: 0.12, y: -1, z: 0.08 },
          spread: 1.0,
          color: '#d89a43',
          color2: '#8c5c2b',
          alphaStart: 0.92,
          alphaEnd: 0,
          scaleStart: 1,
          scaleEnd: 0.7,
        },
      ],
    }),
  },
  {
    id: 'embersRiseLite',
    label: 'Embers Rise Lite',
    description: 'Warm ember sparks drifting upward from heat sources.',
    props: clampParticleSystemComponentProps({
      presetId: 'embersRiseLite',
      budget: { qualityTier: 'balanced', maxParticles: 80, spawnRateScale: 0.8, cullDistance: 26, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#ffab4c', emissionRate: 16, burstCount: 18, radius: 0.55, speed: 1.8, lifetime: 2.1, particleSize: 0.1, opacity: 0.78 },
      emitters: [
        {
          id: 'ember_core',
          shape: 'sphere',
          position: { x: 0, y: 0.15, z: 0 },
          size: { x: 0.2, y: 0.2, z: 0.2 },
          radius: 0.5,
          emissionRate: 16,
          emissionBursts: 18,
          maxParticles: 80,
          particleSize: 0.1,
          lifetime: 2.1,
          speed: 1.8,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 0.95,
          color: '#ffab4c',
          color2: '#ffe08a',
          alphaStart: 0.8,
          alphaEnd: 0,
          scaleStart: 0.55,
          scaleEnd: 0.2,
        },
      ],
    }),
  },
  {
    id: 'dustMotesLite',
    label: 'Dust Motes Lite',
    description: 'Tiny floating dust motes for interiors and caves.',
    props: clampParticleSystemComponentProps({
      presetId: 'dustMotesLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 56, spawnRateScale: 0.5, cullDistance: 20, updateHz: 20 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#d8d2c7', emissionRate: 6, burstCount: 8, radius: 0.8, speed: 0.35, lifetime: 6, particleSize: 0.06, opacity: 0.28 },
      render: { textureAssetId: null, blendMode: 'alpha', depthWrite: false, sortOffset: 0, renderMode: 'sprite' },
      emitters: [
        {
          id: 'dust_volume',
          shape: 'box',
          position: { x: 0, y: 1, z: 0 },
          size: { x: 3, y: 1.5, z: 3 },
          radius: 0.8,
          emissionRate: 6,
          emissionBursts: 8,
          maxParticles: 56,
          particleSize: 0.06,
          lifetime: 6,
          speed: 0.35,
          velocityMode: 'vector',
          direction: { x: 0.03, y: 0.22, z: 0.02 },
          spread: 0.3,
          color: '#d8d2c7',
          color2: '#f1ece3',
          alphaStart: 0.28,
          alphaEnd: 0,
          scaleStart: 0.7,
          scaleEnd: 1.3,
        },
      ],
    }),
  },
  {
    id: 'bubbleRiseLite',
    label: 'Bubble Rise Lite',
    description: 'Soft upward bubbles for underwater scenes.',
    props: clampParticleSystemComponentProps({
      presetId: 'bubbleRiseLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 64, spawnRateScale: 0.7, cullDistance: 24, updateHz: 24 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#b8f0ff', emissionRate: 10, burstCount: 12, radius: 0.45, speed: 0.9, lifetime: 4.4, particleSize: 0.16, opacity: 0.45 },
      render: { textureAssetId: null, blendMode: 'alpha', depthWrite: false, sortOffset: 0, renderMode: 'sprite' },
      emitters: [
        {
          id: 'bubble_stream',
          shape: 'box',
          position: { x: 0, y: 0.2, z: 0 },
          size: { x: 0.35, y: 0.2, z: 0.35 },
          radius: 0.45,
          emissionRate: 10,
          emissionBursts: 12,
          maxParticles: 64,
          particleSize: 0.16,
          lifetime: 4.4,
          speed: 0.9,
          velocityMode: 'vector',
          direction: { x: 0.04, y: 1, z: 0.04 },
          spread: 0.5,
          color: '#b8f0ff',
          color2: '#f4feff',
          alphaStart: 0.35,
          alphaEnd: 0,
          scaleStart: 0.5,
          scaleEnd: 1.1,
        },
      ],
    }),
  },
  {
    id: 'fireflyGlowLite',
    label: 'Firefly Glow Lite',
    description: 'Tiny glowing dots for nighttime ambience.',
    props: clampParticleSystemComponentProps({
      presetId: 'fireflyGlowLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 48, spawnRateScale: 0.55, cullDistance: 20, updateHz: 24 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#ffe37a', emissionRate: 8, burstCount: 8, radius: 0.7, speed: 0.5, lifetime: 3.5, particleSize: 0.08, opacity: 0.75 },
      emitters: [
        {
          id: 'firefly_cloud',
          shape: 'sphere',
          position: { x: 0, y: 1.4, z: 0 },
          size: { x: 1, y: 1, z: 1 },
          radius: 0.65,
          emissionRate: 8,
          emissionBursts: 8,
          maxParticles: 48,
          particleSize: 0.08,
          lifetime: 3.5,
          speed: 0.5,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 1.4,
          color: '#ffe37a',
          color2: '#fff9cf',
          alphaStart: 0.75,
          alphaEnd: 0,
          scaleStart: 0.4,
          scaleEnd: 1.0,
        },
      ],
    }),
  },
  {
    id: 'magicSparkleLite',
    label: 'Magic Sparkle Lite',
    description: 'Small glitter sparkles for spells and enchanted UI.',
    props: clampParticleSystemComponentProps({
      presetId: 'magicSparkleLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 64, spawnRateScale: 0.75, cullDistance: 22, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#d5a8ff', emissionRate: 12, burstCount: 16, radius: 0.4, speed: 1.2, lifetime: 1.6, particleSize: 0.08, opacity: 0.85 },
      render: { textureAssetId: null, blendMode: 'additive', depthWrite: false, sortOffset: 0, renderMode: 'sprite' },
      emitters: [
        {
          id: 'sparkle_core',
          shape: 'sphere',
          position: { x: 0, y: 0.3, z: 0 },
          size: { x: 0.15, y: 0.15, z: 0.15 },
          radius: 0.32,
          emissionRate: 12,
          emissionBursts: 16,
          maxParticles: 64,
          particleSize: 0.08,
          lifetime: 1.6,
          speed: 1.2,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 1.4,
          color: '#d5a8ff',
          color2: '#fff4ff',
          alphaStart: 0.9,
          alphaEnd: 0,
          scaleStart: 0.35,
          scaleEnd: 0.1,
        },
      ],
    }),
  },
  {
    id: 'healPulseLite',
    label: 'Heal Pulse Lite',
    description: 'Soft green healing pulse for support skills and recovery.',
    props: clampParticleSystemComponentProps({
      presetId: 'healPulseLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 72, spawnRateScale: 0.8, cullDistance: 24, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#8df59b', emissionRate: 14, burstCount: 18, radius: 0.85, speed: 1.0, lifetime: 1.8, particleSize: 0.13, opacity: 0.8 },
      emitters: [
        {
          id: 'heal_ring',
          shape: 'sphere',
          position: { x: 0, y: 0.1, z: 0 },
          size: { x: 0.2, y: 0.2, z: 0.2 },
          radius: 0.8,
          emissionRate: 14,
          emissionBursts: 18,
          maxParticles: 72,
          particleSize: 0.13,
          lifetime: 1.8,
          speed: 1,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 0.7,
          color: '#8df59b',
          color2: '#e8ffef',
          alphaStart: 0.85,
          alphaEnd: 0,
          scaleStart: 0.5,
          scaleEnd: 0.18,
        },
      ],
    }),
  },
  {
    id: 'shieldAuraLite',
    label: 'Shield Aura Lite',
    description: 'Blue protective aura for buffs and defensive states.',
    props: clampParticleSystemComponentProps({
      presetId: 'shieldAuraLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 72, spawnRateScale: 0.7, cullDistance: 24, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#6fc8ff', emissionRate: 10, burstCount: 12, radius: 1.0, speed: 0.7, lifetime: 2.4, particleSize: 0.12, opacity: 0.65 },
      render: { textureAssetId: null, blendMode: 'additive', depthWrite: false, sortOffset: 0, renderMode: 'sprite' },
      emitters: [
        {
          id: 'shield_shell',
          shape: 'sphere',
          position: { x: 0, y: 0.6, z: 0 },
          size: { x: 0.25, y: 0.25, z: 0.25 },
          radius: 0.9,
          emissionRate: 10,
          emissionBursts: 12,
          maxParticles: 72,
          particleSize: 0.12,
          lifetime: 2.4,
          speed: 0.7,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 0.9,
          color: '#6fc8ff',
          color2: '#d8f5ff',
          alphaStart: 0.7,
          alphaEnd: 0,
          scaleStart: 0.55,
          scaleEnd: 0.18,
        },
      ],
    }),
  },
  {
    id: 'levelUpBurstLite',
    label: 'Level Up Burst Lite',
    description: 'Celebratory vertical burst for level-up and rank-up moments.',
    props: clampParticleSystemComponentProps({
      presetId: 'levelUpBurstLite',
      playback: { autoPlay: false, loop: false, startActive: false, prewarmSeconds: 0, softStopSeconds: 0.15 },
      budget: { qualityTier: 'mini-safe', maxParticles: 48, spawnRateScale: 1, cullDistance: 20, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#ffe27a', emissionRate: 0, burstCount: 24, radius: 0.2, speed: 3.2, lifetime: 1.0, particleSize: 0.11, opacity: 0.95 },
      emitters: [
        {
          id: 'level_up',
          shape: 'point',
          position: { x: 0, y: 0.2, z: 0 },
          size: { x: 0, y: 0, z: 0 },
          radius: 0.2,
          emissionRate: 0,
          emissionBursts: 24,
          maxParticles: 48,
          particleSize: 0.11,
          lifetime: 1.0,
          speed: 3.2,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 1.8,
          color: '#ffe27a',
          color2: '#fff3be',
          alphaStart: 1,
          alphaEnd: 0,
          scaleStart: 0.8,
          scaleEnd: 0.18,
        },
      ],
    }),
  },
  {
    id: 'coinPickupLite',
    label: 'Coin Pickup Lite',
    description: 'Gold burst for coins, pickups, and rewards.',
    props: clampParticleSystemComponentProps({
      presetId: 'coinPickupLite',
      playback: { autoPlay: false, loop: false, startActive: false, prewarmSeconds: 0, softStopSeconds: 0.1 },
      budget: { qualityTier: 'mini-safe', maxParticles: 40, spawnRateScale: 1, cullDistance: 18, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#ffc84d', emissionRate: 0, burstCount: 16, radius: 0.18, speed: 2.6, lifetime: 0.8, particleSize: 0.08, opacity: 0.95 },
      emitters: [
        {
          id: 'coin_glint',
          shape: 'point',
          position: { x: 0, y: 0.15, z: 0 },
          size: { x: 0, y: 0, z: 0 },
          radius: 0.18,
          emissionRate: 0,
          emissionBursts: 16,
          maxParticles: 40,
          particleSize: 0.08,
          lifetime: 0.8,
          speed: 2.6,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 2.2,
          color: '#ffc84d',
          color2: '#fff0aa',
          alphaStart: 1,
          alphaEnd: 0,
          scaleStart: 0.75,
          scaleEnd: 0.15,
        },
      ],
    }),
  },
  {
    id: 'itemPickupLite',
    label: 'Item Pickup Lite',
    description: 'Small white-gold pickup burst for inventory and loot.',
    props: clampParticleSystemComponentProps({
      presetId: 'itemPickupLite',
      playback: { autoPlay: false, loop: false, startActive: false, prewarmSeconds: 0, softStopSeconds: 0.1 },
      budget: { qualityTier: 'mini-safe', maxParticles: 40, spawnRateScale: 1, cullDistance: 18, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#fff7d1', emissionRate: 0, burstCount: 14, radius: 0.16, speed: 2.2, lifetime: 0.9, particleSize: 0.08, opacity: 0.9 },
      emitters: [
        {
          id: 'loot_glint',
          shape: 'point',
          position: { x: 0, y: 0.12, z: 0 },
          size: { x: 0, y: 0, z: 0 },
          radius: 0.16,
          emissionRate: 0,
          emissionBursts: 14,
          maxParticles: 40,
          particleSize: 0.08,
          lifetime: 0.9,
          speed: 2.2,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 2.0,
          color: '#fff7d1',
          color2: '#ffffff',
          alphaStart: 0.95,
          alphaEnd: 0,
          scaleStart: 0.7,
          scaleEnd: 0.15,
        },
      ],
    }),
  },
  {
    id: 'impactDebrisLite',
    label: 'Impact Debris Lite',
    description: 'Small brown debris burst for hits and collision impacts.',
    props: clampParticleSystemComponentProps({
      presetId: 'impactDebrisLite',
      playback: { autoPlay: false, loop: false, startActive: false, prewarmSeconds: 0, softStopSeconds: 0.12 },
      budget: { qualityTier: 'mini-safe', maxParticles: 48, spawnRateScale: 1, cullDistance: 18, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#c79a68', emissionRate: 0, burstCount: 20, radius: 0.2, speed: 3.1, lifetime: 0.9, particleSize: 0.07, opacity: 0.92 },
      emitters: [
        {
          id: 'debris_burst',
          shape: 'point',
          position: { x: 0, y: 0.1, z: 0 },
          size: { x: 0, y: 0, z: 0 },
          radius: 0.2,
          emissionRate: 0,
          emissionBursts: 20,
          maxParticles: 48,
          particleSize: 0.07,
          lifetime: 0.9,
          speed: 3.1,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 2.5,
          color: '#c79a68',
          color2: '#8c6a49',
          alphaStart: 1,
          alphaEnd: 0,
          scaleStart: 0.6,
          scaleEnd: 0.2,
        },
      ],
    }),
  },
  {
    id: 'explosionFlashLite',
    label: 'Explosion Flash Lite',
    description: 'Bright orange explosion burst for combat and destruction.',
    props: clampParticleSystemComponentProps({
      presetId: 'explosionFlashLite',
      playback: { autoPlay: false, loop: false, startActive: false, prewarmSeconds: 0, softStopSeconds: 0.08 },
      budget: { qualityTier: 'mini-safe', maxParticles: 64, spawnRateScale: 1, cullDistance: 20, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#ff9b53', emissionRate: 0, burstCount: 30, radius: 0.24, speed: 4.2, lifetime: 0.8, particleSize: 0.1, opacity: 0.98 },
      emitters: [
        {
          id: 'explosion_core',
          shape: 'sphere',
          position: { x: 0, y: 0.15, z: 0 },
          size: { x: 0.2, y: 0.2, z: 0.2 },
          radius: 0.22,
          emissionRate: 0,
          emissionBursts: 30,
          maxParticles: 64,
          particleSize: 0.1,
          lifetime: 0.8,
          speed: 4.2,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 2.8,
          color: '#ff9b53',
          color2: '#ffe39b',
          alphaStart: 1,
          alphaEnd: 0,
          scaleStart: 0.9,
          scaleEnd: 0.18,
        },
      ],
    }),
  },
  {
    id: 'teleportMistLite',
    label: 'Teleport Mist Lite',
    description: 'Mystic purple mist for warp and teleport transitions.',
    props: clampParticleSystemComponentProps({
      presetId: 'teleportMistLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 72, spawnRateScale: 0.8, cullDistance: 24, updateHz: 24 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#9d7bff', emissionRate: 12, burstCount: 12, radius: 0.9, speed: 0.9, lifetime: 2.6, particleSize: 0.18, opacity: 0.52 },
      render: { textureAssetId: null, blendMode: 'alpha', depthWrite: false, sortOffset: 0, renderMode: 'sprite' },
      emitters: [
        {
          id: 'teleport_fog',
          shape: 'box',
          position: { x: 0, y: 0.18, z: 0 },
          size: { x: 0.6, y: 0.25, z: 0.6 },
          radius: 0.9,
          emissionRate: 12,
          emissionBursts: 12,
          maxParticles: 72,
          particleSize: 0.18,
          lifetime: 2.6,
          speed: 0.9,
          velocityMode: 'vector',
          direction: { x: 0.04, y: 1, z: 0.04 },
          spread: 0.8,
          color: '#9d7bff',
          color2: '#d5c4ff',
          alphaStart: 0.5,
          alphaEnd: 0,
          scaleStart: 0.7,
          scaleEnd: 1.4,
        },
      ],
    }),
  },
  {
    id: 'portalSwirlLite',
    label: 'Portal Swirl Lite',
    description: 'Cyan portal haze with rising motion for gateway scenes.',
    props: clampParticleSystemComponentProps({
      presetId: 'portalSwirlLite',
      budget: { qualityTier: 'balanced', maxParticles: 88, spawnRateScale: 0.8, cullDistance: 28, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#63f0ff', emissionRate: 18, burstCount: 18, radius: 0.85, speed: 1.4, lifetime: 2.2, particleSize: 0.14, opacity: 0.7 },
      emitters: [
        {
          id: 'portal_core',
          shape: 'sphere',
          position: { x: 0, y: 0.6, z: 0 },
          size: { x: 0.3, y: 0.3, z: 0.3 },
          radius: 0.8,
          emissionRate: 18,
          emissionBursts: 18,
          maxParticles: 88,
          particleSize: 0.14,
          lifetime: 2.2,
          speed: 1.4,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 0.7,
          color: '#63f0ff',
          color2: '#d8ffff',
          alphaStart: 0.72,
          alphaEnd: 0,
          scaleStart: 0.75,
          scaleEnd: 0.22,
        },
      ],
    }),
  },
  {
    id: 'poisonPuffLite',
    label: 'Poison Puff Lite',
    description: 'Sickly green puff for poison and toxic status effects.',
    props: clampParticleSystemComponentProps({
      presetId: 'poisonPuffLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 64, spawnRateScale: 0.7, cullDistance: 22, updateHz: 24 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#8bd96c', emissionRate: 10, burstCount: 12, radius: 0.55, speed: 0.6, lifetime: 2.8, particleSize: 0.18, opacity: 0.5 },
      render: { textureAssetId: null, blendMode: 'alpha', depthWrite: false, sortOffset: 0, renderMode: 'sprite' },
      emitters: [
        {
          id: 'toxic_smoke',
          shape: 'box',
          position: { x: 0, y: 0.2, z: 0 },
          size: { x: 0.4, y: 0.2, z: 0.4 },
          radius: 0.55,
          emissionRate: 10,
          emissionBursts: 12,
          maxParticles: 64,
          particleSize: 0.18,
          lifetime: 2.8,
          speed: 0.6,
          velocityMode: 'vector',
          direction: { x: 0.08, y: 1, z: 0.08 },
          spread: 0.55,
          color: '#8bd96c',
          color2: '#d7ffb5',
          alphaStart: 0.55,
          alphaEnd: 0,
          scaleStart: 0.8,
          scaleEnd: 1.35,
        },
      ],
    }),
  },
  {
    id: 'buffAuraLite',
    label: 'Buff Aura Lite',
    description: 'Positive status aura for power-ups and temporary boosts.',
    props: clampParticleSystemComponentProps({
      presetId: 'buffAuraLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 72, spawnRateScale: 0.8, cullDistance: 24, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#77ffd9', emissionRate: 14, burstCount: 14, radius: 0.85, speed: 0.95, lifetime: 2.2, particleSize: 0.12, opacity: 0.72 },
      emitters: [
        {
          id: 'buff_shell',
          shape: 'sphere',
          position: { x: 0, y: 0.7, z: 0 },
          size: { x: 0.22, y: 0.22, z: 0.22 },
          radius: 0.82,
          emissionRate: 14,
          emissionBursts: 14,
          maxParticles: 72,
          particleSize: 0.12,
          lifetime: 2.2,
          speed: 0.95,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 0.75,
          color: '#77ffd9',
          color2: '#dffff7',
          alphaStart: 0.75,
          alphaEnd: 0,
          scaleStart: 0.6,
          scaleEnd: 0.2,
        },
      ],
    }),
  },
  {
    id: 'debuffSmokeLite',
    label: 'Debuff Smoke Lite',
    description: 'Dark smoke for slowing, weakness, and negative states.',
    props: clampParticleSystemComponentProps({
      presetId: 'debuffSmokeLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 64, spawnRateScale: 0.75, cullDistance: 22, updateHz: 24 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#8e95a3', emissionRate: 10, burstCount: 12, radius: 0.55, speed: 0.5, lifetime: 2.8, particleSize: 0.2, opacity: 0.42 },
      render: { textureAssetId: null, blendMode: 'alpha', depthWrite: false, sortOffset: 0, renderMode: 'sprite' },
      emitters: [
        {
          id: 'debuff_cloud',
          shape: 'box',
          position: { x: 0, y: 0.2, z: 0 },
          size: { x: 0.45, y: 0.2, z: 0.45 },
          radius: 0.55,
          emissionRate: 10,
          emissionBursts: 12,
          maxParticles: 64,
          particleSize: 0.2,
          lifetime: 2.8,
          speed: 0.5,
          velocityMode: 'vector',
          direction: { x: -0.05, y: 0.9, z: 0.05 },
          spread: 0.6,
          color: '#8e95a3',
          color2: '#c9ced6',
          alphaStart: 0.42,
          alphaEnd: 0,
          scaleStart: 0.8,
          scaleEnd: 1.3,
        },
      ],
    }),
  },
  {
    id: 'thunderZapLite',
    label: 'Thunder Zap Lite',
    description: 'Blue lightning spark burst for electric hits and stun effects.',
    props: clampParticleSystemComponentProps({
      presetId: 'thunderZapLite',
      playback: { autoPlay: false, loop: false, startActive: false, prewarmSeconds: 0, softStopSeconds: 0.08 },
      budget: { qualityTier: 'mini-safe', maxParticles: 56, spawnRateScale: 1, cullDistance: 18, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#67d8ff', emissionRate: 0, burstCount: 18, radius: 0.18, speed: 4.8, lifetime: 0.75, particleSize: 0.08, opacity: 0.95 },
      emitters: [
        {
          id: 'zap_core',
          shape: 'point',
          position: { x: 0, y: 0.18, z: 0 },
          size: { x: 0, y: 0, z: 0 },
          radius: 0.18,
          emissionRate: 0,
          emissionBursts: 18,
          maxParticles: 56,
          particleSize: 0.08,
          lifetime: 0.75,
          speed: 4.8,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 2.9,
          color: '#67d8ff',
          color2: '#ffffff',
          alphaStart: 1,
          alphaEnd: 0,
          scaleStart: 0.8,
          scaleEnd: 0.15,
        },
      ],
    }),
  },
  {
    id: 'windGustLite',
    label: 'Wind Gust Lite',
    description: 'Directional streaks for strong wind and motion cues.',
    props: clampParticleSystemComponentProps({
      presetId: 'windGustLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 72, spawnRateScale: 0.8, cullDistance: 30, updateHz: 24 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#f0f7ff', emissionRate: 16, burstCount: 18, radius: 1.4, speed: 2.8, lifetime: 1.4, particleSize: 0.06, opacity: 0.5 },
      render: { textureAssetId: null, blendMode: 'alpha', depthWrite: false, sortOffset: 0, renderMode: 'sprite' },
      emitters: [
        {
          id: 'wind_sheet',
          shape: 'box',
          position: { x: 0, y: 1.5, z: 0 },
          size: { x: 3.8, y: 0.4, z: 0.4 },
          radius: 1.4,
          emissionRate: 16,
          emissionBursts: 18,
          maxParticles: 72,
          particleSize: 0.06,
          lifetime: 1.4,
          speed: 2.8,
          velocityMode: 'vector',
          direction: { x: 1, y: 0, z: 0 },
          spread: 0.28,
          color: '#f0f7ff',
          color2: '#d9eaff',
          alphaStart: 0.45,
          alphaEnd: 0,
          scaleStart: 0.75,
          scaleEnd: 0.4,
        },
      ],
    }),
  },
  {
    id: 'waterSplashLite',
    label: 'Water Splash Lite',
    description: 'Splash burst for water impacts and jump landings.',
    props: clampParticleSystemComponentProps({
      presetId: 'waterSplashLite',
      playback: { autoPlay: false, loop: false, startActive: false, prewarmSeconds: 0, softStopSeconds: 0.08 },
      budget: { qualityTier: 'mini-safe', maxParticles: 64, spawnRateScale: 1, cullDistance: 20, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#8fe9ff', emissionRate: 0, burstCount: 24, radius: 0.2, speed: 3.6, lifetime: 1.0, particleSize: 0.08, opacity: 0.9 },
      emitters: [
        {
          id: 'splash_core',
          shape: 'sphere',
          position: { x: 0, y: 0.1, z: 0 },
          size: { x: 0.16, y: 0.16, z: 0.16 },
          radius: 0.18,
          emissionRate: 0,
          emissionBursts: 24,
          maxParticles: 64,
          particleSize: 0.08,
          lifetime: 1,
          speed: 3.6,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 2.3,
          color: '#8fe9ff',
          color2: '#ffffff',
          alphaStart: 1,
          alphaEnd: 0,
          scaleStart: 0.8,
          scaleEnd: 0.18,
        },
      ],
    }),
  },
  {
    id: 'lavaSplashLite',
    label: 'Lava Splash Lite',
    description: 'Hot orange-red splash for lava and magma impacts.',
    props: clampParticleSystemComponentProps({
      presetId: 'lavaSplashLite',
      playback: { autoPlay: false, loop: false, startActive: false, prewarmSeconds: 0, softStopSeconds: 0.08 },
      budget: { qualityTier: 'mini-safe', maxParticles: 64, spawnRateScale: 1, cullDistance: 20, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#ff8a3d', emissionRate: 0, burstCount: 24, radius: 0.2, speed: 3.8, lifetime: 0.95, particleSize: 0.09, opacity: 0.98 },
      emitters: [
        {
          id: 'lava_core',
          shape: 'sphere',
          position: { x: 0, y: 0.12, z: 0 },
          size: { x: 0.16, y: 0.16, z: 0.16 },
          radius: 0.18,
          emissionRate: 0,
          emissionBursts: 24,
          maxParticles: 64,
          particleSize: 0.09,
          lifetime: 0.95,
          speed: 3.8,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 2.3,
          color: '#ff8a3d',
          color2: '#ffd36f',
          alphaStart: 1,
          alphaEnd: 0,
          scaleStart: 0.85,
          scaleEnd: 0.18,
        },
      ],
    }),
  },
  {
    id: 'frostMistLite',
    label: 'Frost Mist Lite',
    description: 'Cold blue mist for frozen zones and ice magic.',
    props: clampParticleSystemComponentProps({
      presetId: 'frostMistLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 72, spawnRateScale: 0.75, cullDistance: 22, updateHz: 24 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#c9f0ff', emissionRate: 12, burstCount: 12, radius: 0.8, speed: 0.7, lifetime: 3.0, particleSize: 0.16, opacity: 0.42 },
      render: { textureAssetId: null, blendMode: 'alpha', depthWrite: false, sortOffset: 0, renderMode: 'sprite' },
      emitters: [
        {
          id: 'frost_cloud',
          shape: 'box',
          position: { x: 0, y: 0.25, z: 0 },
          size: { x: 0.55, y: 0.2, z: 0.55 },
          radius: 0.8,
          emissionRate: 12,
          emissionBursts: 12,
          maxParticles: 72,
          particleSize: 0.16,
          lifetime: 3.0,
          speed: 0.7,
          velocityMode: 'vector',
          direction: { x: 0.05, y: 0.95, z: 0.05 },
          spread: 0.55,
          color: '#c9f0ff',
          color2: '#f7fdff',
          alphaStart: 0.42,
          alphaEnd: 0,
          scaleStart: 0.8,
          scaleEnd: 1.3,
        },
      ],
    }),
  },
  {
    id: 'energyTrailLite',
    label: 'Energy Trail Lite',
    description: 'Short flowing streaks for movement trails and dashes.',
    props: clampParticleSystemComponentProps({
      presetId: 'energyTrailLite',
      budget: { qualityTier: 'mini-safe', maxParticles: 72, spawnRateScale: 0.8, cullDistance: 24, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#7feeff', emissionRate: 18, burstCount: 16, radius: 0.35, speed: 2.4, lifetime: 1.2, particleSize: 0.06, opacity: 0.85 },
      render: { textureAssetId: null, blendMode: 'additive', depthWrite: false, sortOffset: 0, renderMode: 'sprite' },
      emitters: [
        {
          id: 'trail_stream',
          shape: 'box',
          position: { x: 0, y: 0.05, z: 0 },
          size: { x: 0.2, y: 0.2, z: 0.2 },
          radius: 0.35,
          emissionRate: 18,
          emissionBursts: 16,
          maxParticles: 72,
          particleSize: 0.06,
          lifetime: 1.2,
          speed: 2.4,
          velocityMode: 'vector',
          direction: { x: 0, y: 1, z: 0 },
          spread: 0.4,
          color: '#7feeff',
          color2: '#ffffff',
          alphaStart: 0.85,
          alphaEnd: 0,
          scaleStart: 0.45,
          scaleEnd: 0.1,
        },
      ],
    }),
  },
  {
    id: 'beamHitLite',
    label: 'Beam Hit Lite',
    description: 'Quick white-blue burst for laser and beam impacts.',
    props: clampParticleSystemComponentProps({
      presetId: 'beamHitLite',
      playback: { autoPlay: false, loop: false, startActive: false, prewarmSeconds: 0, softStopSeconds: 0.08 },
      budget: { qualityTier: 'mini-safe', maxParticles: 48, spawnRateScale: 1, cullDistance: 18, updateHz: 30 },
      exposedParams: { ...DEFAULT_PARTICLE_EXPOSED_PARAMS, color: '#e8f7ff', emissionRate: 0, burstCount: 18, radius: 0.18, speed: 4.2, lifetime: 0.7, particleSize: 0.08, opacity: 1 },
      emitters: [
        {
          id: 'beam_flash',
          shape: 'point',
          position: { x: 0, y: 0.1, z: 0 },
          size: { x: 0, y: 0, z: 0 },
          radius: 0.18,
          emissionRate: 0,
          emissionBursts: 18,
          maxParticles: 48,
          particleSize: 0.08,
          lifetime: 0.7,
          speed: 4.2,
          velocityMode: 'radial',
          direction: { x: 0, y: 1, z: 0 },
          spread: 2.6,
          color: '#e8f7ff',
          color2: '#9edcff',
          alphaStart: 1,
          alphaEnd: 0,
          scaleStart: 0.75,
          scaleEnd: 0.15,
        },
      ],
    }),
  },
]

const PRESET_MAP = new Map(PRESETS.map((entry) => [entry.id, entry]))

export function listParticlePresets(): ParticlePresetDefinition[] {
  return PRESETS.map((entry) => ({
    ...entry,
    props: cloneParticleSystemComponentProps(entry.props),
  }))
}

export function getParticlePresetDefinition(id: string | null | undefined): ParticlePresetDefinition | null {
  const normalized = typeof id === 'string' ? id.trim() : ''
  const found = normalized ? PRESET_MAP.get(normalized) ?? null : null
  if (!found) {
    return null
  }
  return {
    ...found,
    props: cloneParticleSystemComponentProps(found.props),
  }
}

export function createParticlePresetProps(id: string | null | undefined): ParticleSystemComponentProps {
  const found = getParticlePresetDefinition(id)
  return cloneParticleSystemComponentProps(found?.props ?? PRESETS[0]!.props)
}
